### ISSUE TITLE
Cached error messages point to incorrect asserts

### ISSUE THREAD

**Issue by viper-admin** [viperproject/viper-ide#106] opened 2019-11-15 15:22 UTC
> Created by bitbucket user **OmerSakar** on 2019-11-15 15:22

In the code below, a variable `a` is defined, the value of `a` is set to 2, it is asserted to be 2, the value is set to 4 and is asserted to be 2. One expects the first assertion to pass and the second assertion to fail.

Using VSCode with the Viper plugin version 2.2.1 installed the following happens. The first time \(without any cache\) the first assertion passes and the second fails. If we, for example, add a space at the end of a line to let Viper run again, the first assertion fails. The error message mentions that it is from cache.

```
method foo() {
  var a: Int
  a := 2
  assert a == 2 // Assertion 1, should pass
  a := 4
  assert a == 2 // Assertion 2, should fail
}
```

It seems that if an assertion is used twice and the second assertion should fail, then the next time Viper runs the error message in the cache points to the wrong assertion. For example, if the second assertion is replaced by `assert a == 2 || false` which is equivalent and should still fail, then the error message always points to the second assertion. However if that same assertion is used somewhere where it should pass \(as in the code snippet below\), then the cache will point to the first assertion \(which should pass\) instead of the real culprit \(i.e. the second assertion which should fail\).

```
method foo() {
  var a: Int
  a := 2
  assert a == 2               // Assertion 1, should pass
  assert a == 2 || false      // Assertion 2, should pass
  a := 4
  assert a == 2 || false      // Assertion 2, should fail
}
```

‌

‌

**Comment by ArquintL** [comment] 2021-07-19 06:53
Duplicate of [Viper-IDE #23](https://github.com/viperproject/viperserver/issues/23). This is already fixed

**Closed by ArquintL** 2021-07-19 06:53 UTC
Labels: bug, major
