### ISSUE TITLE
Viper extension v2.4.1: Viper language server crashes.

### ISSUE THREAD

**Issue by roberthoenig** [viperproject/viper-ide#254] opened 2022-04-14 11:42 UTC
The Viper language server crashes in VSCode after I updated the Viper VSCode extension:

```
internal/modules/cjs/loader.js:937
  throw err;
  ^

Error: Cannot find module 'node:events'
Require stack:
- /home/robert/.vscode/extensions/viper-admin.viper-2.4.1/server/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Module.6883 (/home/robert/.vscode/extensions/viper-admin.viper-2.4.1/server/index.js:2:1108228)
    at a (/home/robert/.vscode/extensions/viper-admin.viper-2.4.1/server/index.js:2:1702592)
    at Object.6260 (/home/robert/.vscode/extensions/viper-admin.viper-2.4.1/server/index.js:2:788569)
    at a (/home/robert/.vscode/extensions/viper-admin.viper-2.4.1/server/index.js:2:1702592)
    at Object.7180 (/home/robert/.vscode/extensions/viper-admin.viper-2.4.1/server/index.js:2:795579) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/robert/.vscode/extensions/viper-admin.viper-2.4.1/server/index.js'
  ]
}
[Info  - 1:38:22 PM] Connection to server got closed. Server will restart.
```

Operating System: Ubuntu 20.04.1
VSCode version: 1.65.2

**Comment by fpoli** [comment] 2022-05-11 14:40
I'm experiencing the same.

**Comment by ArquintL** [comment] 2022-05-16 13:29
> I'm experiencing the same.

@fpoli two questions:
 - do you observe the crash at the very beginning, after basically doing no interaction at all?
 - do you use the same VSCode version? Is it reproducible if the latest VSCode version?

My thoughts:
- looks like resolving the built-in module does not work, presumably because it's expecting `'events'` but gets `'node:events'`.
- `'node:events'` is a newer naming in node but that should already be around for a couple of years now
- I think I've observed a similar problem on my machine but I don't have any clue anymore how I've fixed it back then. Spontaneously, the error might have gone away after updating VSCode

**Comment by fpoli** [comment] 2022-05-16 14:37
Version 2.3.1 seems to work fine.

> do you observe the crash at the very beginning, after basically doing no interaction at all?

Yes

> do you use the same VSCode version? Is it reproducible if the latest VSCode version?

No, an older one. My VSCode:

Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:01:43.795Z (7 mos ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 4.15.0-142-generic

I'll try updating VSCode

**Comment by fpoli** [comment] 2022-05-16 14:42
Updating VSCode solved the issue. I can use the Viper IDE v2.4.2. We should update the `"engines"` field of the `package.json` of the Viper IDE to something between 1.65.2 and 1.67.1.

Now:
Version: 1.67.1
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:39:22.915Z (1 wk ago)
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 4.15.0-142-generic

**Closed** 2022-07-05 16:43 UTC
